# Generated by Django 4.1.4 on 2023-02-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=6, unique=True, verbose_name='Номер самоката')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('charge', models.CharField(max_length=4, verbose_name='Заряд')),
                ('active', models.CharField(choices=[('Free', 'Свободный'), ('Charge', 'Заряжается'), ('Repair', 'На ремонте'), ('Is used', 'Используется')], default='Free', max_length=255, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(verbose_name='Стоимость поездки')),
                ('date_of_trip', models.DateField(verbose_name='Дата поездки')),
            ],
        ),
    ]
